- name: Install and configure Nginx with dynamic server name
  hosts: webservers
  become: yes

  vars:
    nginx_servers:
      - {
          server_name: "{{ ansible_facts['hostname'] }}",
          port: 80,
          proxy_pass: "backend1",
        }
      - {
          server_name: "{{ ansible_facts['hostname'] }}",
          port: 80,
          proxy_pass: "backend2",
        }

  tasks:
    - name: ensure Nginx is intalled
      when: ansible_facts["os_family"] == "Debian"
      apt:
        name: nginx
        state: present

    - name: Create Nginx configuration from template
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Reload Nginx

    - name: Ensure Nginx is running and enabled
      when: ansible_facts["os_family"] == "Debian"
      service:
        name: nginx
        state: started
        enabled: true

  handlers:
    - name: Reload Nginx
      when: ansible_facts["os_family"] == "Debian"
      service:
        name: nginx
        state: reloaded
